### ISSUE TITLE
Problems with Installation

### ISSUE THREAD

**Issue by JohnBaku** [fetlife/fetlife-ios#12]
Got the following feedback from someone who recently installed the app:

> I had to add ".local" to the "Build Identifier" and then click "Fix issue" just below it, (not in the scree shot).

![fetlife_xcodeproj](https://cloud.githubusercontent.com/assets/22100/14721437/32eccb2e-07bb-11e6-88cb-048d1d60d9ad.png)

and

> Once it was installed in the iPhone I had to go into Setting->General->Device Management->"Profile Name"​ and then approve the FetLife app.

**Comment by jacortinas** [comment]
@JohnBaku can this be closed?

**Comment by JohnBaku** [comment]
@jacortinas I created this before I saw the other PR. If the other PR fixes this then for sure... just please link to it and close it! Thanks.

**Comment by jacortinas** [comment]
Fixed (made better) by #9. Closing this issue.
