### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by mikeakers** [fetlife/fetlife-ios#17]
Hi folks! I'd love to contribute to this project but my employer has a process that needs to be followed before I can start sending you guys pull requests. The good news is that the process is it's usually automatic and instant, but their approval system looks for a LICENSE or COPYING file at the root of the repo containing the projects license. Can you add this file? It should just include the text of the MIT license. 

### Steps to reproduce

1. Clone the repo.
2. Look for a LICENSE or COPYING file at the root of the repo.

### Expected behavior

There should be a LICENSE or COPYING file at the root of the repo containing the projects license.

### Actual behavior

There is no LICENSE or COPYING file at the root of the repo containing the projects license.

### Device Info

N/A

**Comment by JohnBaku** [comment]
@mikeakers hey make.... woot woot.. super happy that you want to contribute! 

Mind if I ask why the license being in the README is not adequate?

**Comment by mikeakers** [comment]
We have an automated system that takes the url of a github repo, looks for the presence of the LICENSE file and verifies that it's one of the licenses we are ok contributing to. It also verifies that the project and org running the project are ones that we don't have issues with people making contributions to.

Putting the license as a link in the readme means I can't use the automated system for instant approval and instead would have to wait for a manual review by a human, which can take a while.

**Comment by reneklacan** [comment]
To me it sounds like a good reason to add a LICENSE file
