### ISSUE TITLE
Screenshots of App

### ISSUE THREAD

**Issue by JohnBaku** [fetlife/fetlife-ios#2]
It's not ideal to include a screenshot of the app because that means we have to keep them up to date but I think that it would be nice to at least have one screenshot of the app in the README so that anyone checking out the repo would get a feel for the app.

Anyway we can add one? I know we have some lying around.

**Comment by jacortinas** [comment]
@JohnBaku Good idea :+1:

**Comment by jacortinas** [comment]
![5 5convoscreen](https://cloud.githubusercontent.com/assets/171215/14657660/d67be15c-0654-11e6-8f8e-937476c98a60.png)

**Comment by jacortinas** [comment]
![5 5convoscreen](https://cloud.githubusercontent.com/assets/171215/14657747/32b8daf6-0655-11e6-9629-11df51b569b7.png)

**Comment by jacortinas** [comment]
@JohnBaku Added #3 to update the README with a screenshot. Please check it out.

**Comment by jacortinas** [comment]
@JohnBaku Closing this after your updates in #4 😄  :+1:

**Comment by JohnBaku** [comment]
@jacortinas thanks!
