### ISSUE TITLE
So currently uninstallable without Mac?

### ISSUE THREAD

**Issue by karakaren** [fetlife/fetlife-ios#7]
I don't have a Mac at home :/

**Comment by JohnBaku** [comment]
I am sorry... you can't from what I understand! :-/ @jacortinas you have any suggestions?

**Comment by jacortinas** [comment]
@karakaren Correct, you currently need a Mac to do the installation from Mac to iOS device.

**Comment by JohnBaku** [comment]
@jacortinas how about we add an FAQ section to our README and add this info to it?

**Comment by jacortinas** [comment]
@JohnBaku :+1:

**Comment by Sherri-Welker** [comment]
Will there be a Windows to ISO download option?

**Comment by jacortinas** [comment]
@Dnscouple45 I'm afraid I've never heard of a Windows to ISO download option for iOS apps. 😅  Could you explain to me what you mean?

Apple allows apps to be distributed as installable archives known as IPA's and that's a possibility for Windows installation but we're still looking into it. 😄

**Comment by alias1** [comment]
Not sure if it would work in this case/at scale, but would it be possible to get around this by using testflight/a similar service? May draw unwanted attention from apple though..

**Comment by Daddy** [comment]
@alias1 Apple does reserve the right to remove apps from Test flight (especially for abuse), although in most cases they will not care. The only concerns with this is while there can be complete transparency about what is being installed by manually installing via Mac for iOS, or downloading the official .apk for Android; testflight could allow a malicious author to make changes to collect user information, etc and provide a link to it on FetLife or in local communities.

**Comment by alias1** [comment]
That's fair enough. I was more thinking at an official FL run TestFlight.

Get Outlook for iOS




On Tue, Jul 12, 2016 at 6:34 AM +1000, "Tyler Corsair" <notifications@github.com> wrote:












@alias1 Apple does reserve the right to remove apps from Test flight (especially for abuse), although in most cases they will not care. The only concerns with this is while there can be complete transparency about what is being installed by manually installing via Mac for iOS, or downloading the official .apk for Android; testflight could allow a malicious author to make changes to collect user information, etc and provide a link to it on FetLife or in local communities.
